### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by miqueiasdesouza** [realtime-framework/MessagingIonicChat#4]
Hi.

This error show me

0     228968   error    Uncaught ReferenceError: Promise is not defined, http://192.168.1.100:8100/plugins/co.realtime.plugins.CordovaPush/www/OrtcPlugin.js, Line: 7

Help me please

**Comment by realtime-framework** [comment]
Are you running the app in a real mobile device or emulator? The Realtime Push Plugin is a native one, so it must be used in a real device/emulator, it won't work in a desktop browser.

**Comment by miqueiasdesouza** [comment]
Hi,
Thanks. I installing Promisse plugin and solved my problem

Enviado do meu iPhone

Em 15 de set de 2017, às 06:14, Realtime Framework <notifications@github.com<mailto:notifications@github.com>> escreveu:


Are you running the app in a real mobile device or emulator? The Realtime Push Plugin is a native one, so it must be used in a real device/emulator, it won't work in a desktop browser.

**Comment by realtime-framework** [comment]
Cool! Let us know if you find any other issues.
